declare module 'vue-codemirror'
declare module 'vue-draggable-resizable'
declare module 'solhint/lib/index'
declare module 'web3-utils'
declare module 'aion-web3'
declare module 'aion-browser-solc'
declare module 'vue-analytics'
